addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mima" % "0.8.2")
