addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.12.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.7.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mima" % "0.7.0")
